/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hda_hdajni_ndk_hdaJniApi */

#ifndef _Included_com_hda_hdajni_ndk_hdaJniApi
#define _Included_com_hda_hdajni_ndk_hdaJniApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hda_hdajni_ndk_hdaJniApi
 * Method:    getLibVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hda_hdajni_ndk_hdaJniApi_getLibVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
